name = "ideaflow-api"
main = "./server.js"
compatibility_date = "2024-01-19"

[vars]
FIREBASE_PROJECT_ID = "ai-ideagenproject"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@ai-ideagenproject.iam.gserviceaccount.com"

# These will be populated by wrangler secret commands
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""
FIREBASE_PRIVATE_KEY = "" 