name = "ideaflow-api"
main = "server.js"
compatibility_date = "2024-01-19"

[vars]
FIREBASE_PROJECT_ID = "ai-ideagenproject"
FIREBASE_API_KEY = "AIzaSyDRVr2UaFxCYwLo-dGPeHVhpYgs6GLOtq8"
FIREBASE_MESSAGING_SENDER_ID = "1234567890"
FIREBASE_APP_ID = "1:1234567890:web:abcdef1234567890"
FIREBASE_DATABASE_URL = "https://ai-ideagenproject.firebaseio.com"
 